<?php

namespace Database\Seeders;

use App\Models\ArsipPKL;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ArsipPKLSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $arsip_pkl = [
            [
                'nim' => '24060121100081',
                'nama' => 'Grace Nguyen',
                'periode_pkl' => '2023/2024 Genap',
                'instansi' => 'PT. ABC',
                'judul' => 'Pengembangan Aplikasi Manajemen Keuangan',
                'abstrak' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed at dui a nunc vestibulum ultricies. Nam condimentum lorem in tortor fermentum, at cursus justo ultricies. In hac habitasse platea dictumst. Nulla non purus arcu. Quisque auctor nulla id sapien mollis ultricies. Donec id elit ut magna euismod auctor. In eu tellus justo. Duis posuere mauris nec leo vestibulum malesuada. Nam eget augue ut leo aliquet egestas non id purus. Nam non luctus felis. Vivamus interdum hendrerit commodo. Nulla at felis ut justo egestas gravida. Aliquam non velit at lorem dictum sodales at at augue. Sed id justo at nisi ullamcorper eleifend a in risus. Donec dignissim libero id lacinia gravida. Integer porta justo vel odio sodales, sit amet facilisis sem volutpat.',
                'keyword1' => 'Aplikasi Manajemen Keuangan',
                'keyword2' => 'Pengembangan',
                'keyword3' => 'Keuangan',
                'link_laporan' => 'drive.google.com',
                'tgl_verif_laporan' => '2024-04-10 00:00:00',
                'nilai' => 'A',
            ],
            [
                'nim' => '24060121100082',
                'nama' => 'Logan King',
                'periode_pkl' => '2023/2024 Genap',
                'instansi' => 'PT. XYZ',
                'judul' => 'Analisis Sistem Informasi Penjualan',
                'abstrak' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed at dui a nunc vestibulum ultricies. Nam condimentum lorem in tortor fermentum, at cursus justo ultricies. In hac habitasse platea dictumst. Nulla non purus arcu. Quisque auctor nulla id sapien mollis ultricies. Donec id elit ut magna euismod auctor. In eu tellus justo. Duis posuere mauris nec leo vestibulum malesuada. Nam eget augue ut leo aliquet egestas non id purus. Nam non luctus felis. Vivamus interdum hendrerit commodo. Nulla at felis ut justo egestas gravida. Aliquam non velit at lorem dictum sodales at at augue. Sed id justo at nisi ullamcorper eleifend a in risus. Donec dignissim libero id lacinia gravida. Integer porta justo vel odio sodales, sit amet facilisis sem volutpat.',
                'keyword1' => 'Sistem Informasi Penjualan',
                'keyword2' => 'Analisis',
                'keyword3' => 'Penjualan',
                'link_laporan' => 'drive.google.com',
                'tgl_verif_laporan' => '2024-04-10 00:00:00',
                'nilai' => 'B',
            ],
            [
                'nim' => '24060121100083',
                'nama' => 'Aria Chavez',
                'periode_pkl' => '2023/2024 Genap',
                'instansi' => 'PT. DEF',
                'judul' => 'Pengembangan Aplikasi Mobile Banking',
                'abstrak' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed at dui a nunc vestibulum ultricies. Nam condimentum lorem in tortor fermentum, at cursus justo ultricies. In hac habitasse platea dictumst. Nulla non purus arcu. Quisque auctor nulla id sapien mollis ultricies. Donec id elit ut magna euismod auctor. In eu tellus justo. Duis posuere mauris nec leo vestibulum malesuada. Nam eget augue ut leo aliquet egestas non id purus. Nam non luctus felis. Vivamus interdum hendrerit commodo. Nulla at felis ut justo egestas gravida. Aliquam non velit at lorem dictum sodales at at augue. Sed id justo at nisi ullamcorper eleifend a in risus. Donec dignissim libero id lacinia gravida. Integer porta justo vel odio sodales, sit amet facilisis sem volutpat.',
                'keyword1' => 'Aplikasi Mobile Banking',
                'keyword2' => 'Pengembangan',
                'keyword3' => 'Banking',
                'link_laporan' => 'drive.google.com',
                'tgl_verif_laporan' => '2024-04-11 00:00:00',
                'nilai' => 'C',
            ],
            [
                'nim' => '24060121100084',
                'nama' => 'Jackson Green',
                'periode_pkl' => '2023/2024 Genap',
                'instansi' => 'PT. GHI',
                'judul' => 'Pengembangan Sistem Informasi Geografis',
                'abstrak' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed at dui a nunc vestibulum ultricies. Nam condimentum lorem in tortor fermentum, at cursus justo ultricies. In hac habitasse platea dictumst. Nulla non purus arcu. Quisque auctor nulla id sapien mollis ultricies. Donec id elit ut magna euismod auctor. In eu tellus justo. Duis posuere mauris nec leo vestibulum malesuada. Nam eget augue ut leo aliquet egestas non id purus. Nam non luctus felis. Vivamus interdum hendrerit commodo. Nulla at felis ut justo egestas gravida. Aliquam non velit at lorem dictum sodales at at augue. Sed id justo at nisi ullamcorper eleifend a in risus. Donec dignissim libero id lacinia gravida. Integer porta justo vel odio sodales, sit amet facilisis sem volutpat.',
                'keyword1' => 'Sistem Informasi Geografis',
                'keyword2' => 'Pengembangan',
                'keyword3' => 'Geografis',
                'link_laporan' => 'drive.google.com',
                'tgl_verif_laporan' => '2024-04-11 00:00:00',
                'nilai' => 'A',
            ],
            [
                'nim' => '24060121100085',
                'nama' => 'Lily Rivera',
                'periode_pkl' => '2023/2024 Genap',
                'instansi' => 'PT. JKL',
                'judul' => 'Analisis dan Perancangan Sistem Informasi Persediaan',
                'abstrak' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed at dui a nunc vestibulum ultricies. Nam condimentum lorem in tortor fermentum, at cursus justo ultricies. In hac habitasse platea dictumst. Nulla non purus arcu. Quisque auctor nulla id sapien mollis ultricies. Donec id elit ut magna euismod auctor. In eu tellus justo. Duis posuere mauris nec leo vestibulum malesuada. Nam eget augue ut leo aliquet egestas non id purus. Nam non luctus felis. Vivamus interdum hendrerit commodo. Nulla at felis ut justo egestas gravida. Aliquam non velit at lorem dictum sodales at at augue. Sed id justo at nisi ullamcorper eleifend a in risus. Donec dignissim libero id lacinia gravida. Integer porta justo vel odio sodales, sit amet facilisis sem volutpat.',
                'keyword1' => 'Sistem Informasi Persediaan',
                'keyword2' => 'Analisis',
                'keyword3' => 'Persediaan',
                'link_laporan' => 'drive.google.com',
                'tgl_verif_laporan' => '2024-04-12 00:00:00',
                'nilai' => 'B',
            ],
            [
                'nim' => '24060121100086',
                'nama' => 'Gabriel Adams',
                'periode_pkl' => '2023/2024 Genap',
                'instansi' => 'PT. MNO',
                'judul' => 'Pengembangan Aplikasi E-Learning',
                'abstrak' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed at dui a nunc vestibulum ultricies. Nam condimentum lorem in tortor fermentum, at cursus justo ultricies. In hac habitasse platea dictumst. Nulla non purus arcu. Quisque auctor nulla id sapien mollis ultricies. Donec id elit ut magna euismod auctor. In eu tellus justo. Duis posuere mauris nec leo vestibulum malesuada. Nam eget augue ut leo aliquet egestas non id purus. Nam non luctus felis. Vivamus interdum hendrerit commodo. Nulla at felis ut justo egestas gravida. Aliquam non velit at lorem dictum sodales at at augue. Sed id justo at nisi ullamcorper eleifend a in risus. Donec dignissim libero id lacinia gravida. Integer porta justo vel odio sodales, sit amet facilisis sem volutpat.',
                'keyword1' => 'Aplikasi E-Learning',
                'keyword2' => 'Pengembangan',
                'keyword3' => 'E-Learning',
                'link_laporan' => 'drive.google.com',
                'tgl_verif_laporan' => '2024-04-12 00:00:00',
                'nilai' => 'A',
            ],
            [
                'nim' => '24060121100087',
                'nama' => 'Addison Mitchell',
                'periode_pkl' => '2023/2024 Genap',
                'instansi' => 'PT. PQR',
                'judul' => 'Analisis dan Perancangan Sistem Informasi Akademik',
                'abstrak' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed at dui a nunc vestibulum ultricies. Nam condimentum lorem in tortor fermentum, at cursus justo ultricies. In hac habitasse platea dictumst. Nulla non purus arcu. Quisque auctor nulla id sapien mollis ultricies. Donec id elit ut magna euismod auctor. In eu tellus justo. Duis posuere mauris nec leo vestibulum malesuada. Nam eget augue ut leo aliquet egestas non id purus. Nam non luctus felis. Vivamus interdum hendrerit commodo. Nulla at felis ut justo egestas gravida. Aliquam non velit at lorem dictum sodales at at augue. Sed id justo at nisi ullamcorper eleifend a in risus. Donec dignissim libero id lacinia gravida. Integer porta justo vel odio sodales, sit amet facilisis sem volutpat.',
                'keyword1' => 'Sistem Informasi Akademik',
                'keyword2' => 'Analisis',
                'keyword3' => 'Akademik',
                'link_laporan' => 'drive.google.com',
                'tgl_verif_laporan' => '2024-04-13 00:00:00',
                'nilai' => 'B',
            ],
            [
                'nim' => '24060121100088',
                'nama' => 'Ryan Hill',
                'periode_pkl' => '2023/2024 Genap',
                'instansi' => 'PT. STU',
                'judul' => 'Pengembangan Aplikasi Pencarian Tempat Wisata',
                'abstrak' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed at dui a nunc vestibulum ultricies. Nam condimentum lorem in tortor fermentum, at cursus justo ultricies. In hac habitasse platea dictumst. Nulla non purus arcu. Quisque auctor nulla id sapien mollis ultricies. Donec id elit ut magna euismod auctor. In eu tellus justo. Duis posuere mauris nec leo vestibulum malesuada. Nam eget augue ut leo aliquet egestas non id purus. Nam non luctus felis. Vivamus interdum hendrerit commodo. Nulla at felis ut justo egestas gravida. Aliquam non velit at lorem dictum sodales at at augue. Sed id justo at nisi ullamcorper eleifend a in risus. Donec dignissim libero id lacinia gravida. Integer porta justo vel odio sodales, sit amet facilisis sem volutpat.',
                'keyword1' => 'Aplikasi Pencarian Tempat Wisata',
                'keyword2' => 'Pengembangan',
                'keyword3' => 'Wisata',
                'link_laporan' => 'drive.google.com',
                'tgl_verif_laporan' => '2024-04-13 00:00:00',
                'nilai' => 'A',
            ],
            [
                'nim' => '24060121100089',
                'nama' => 'Natalie Carter',
                'periode_pkl' => '2023/2024 Genap',
                'instansi' => 'PT. VWX',
                'judul' => 'Analisis dan Perancangan Sistem Informasi Manajemen Inventaris',
                'abstrak' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed at dui a nunc vestibulum ultricies. Nam condimentum lorem in tortor fermentum, at cursus justo ultricies. In hac habitasse platea dictumst. Nulla non purus arcu. Quisque auctor nulla id sapien mollis ultricies. Donec id elit ut magna euismod auctor. In eu tellus justo. Duis posuere mauris nec leo vestibulum malesuada. Nam eget augue ut leo aliquet egestas non id purus. Nam non luctus felis. Vivamus interdum hendrerit commodo. Nulla at felis ut justo egestas gravida. Aliquam non velit at lorem dictum sodales at at augue. Sed id justo at nisi ullamcorper eleifend a in risus. Donec dignissim libero id lacinia gravida. Integer porta justo vel odio sodales, sit amet facilisis sem volutpat.',
                'keyword1' => 'Sistem Informasi Manajemen Inventaris',
                'keyword2' => 'Analisis',
                'keyword3' => 'Inventaris',
                'link_laporan' => 'drive.google.com',
                'tgl_verif_laporan' => '2024-04-14 00:00:00',
                'nilai' => 'B',
            ],
            [
                'nim' => '24060121100090',
                'nama' => 'John Nelson',
                'periode_pkl' => '2023/2024 Genap',
                'instansi' => 'PT. YZB',
                'judul' => 'Analisis dan Perancangan Sistem Informasi Kepegawaian',
                'abstrak' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed at dui a nunc vestibulum ultricies. Nam condimentum lorem in tortor fermentum, at cursus justo ultricies. In hac habitasse platea dictumst. Nulla non purus arcu. Quisque auctor nulla id sapien mollis ultricies. Donec id elit ut magna euismod auctor. In eu tellus justo. Duis posuere mauris nec leo vestibulum malesuada. Nam eget augue ut leo aliquet egestas non id purus. Nam non luctus felis. Vivamus interdum hendrerit commodo. Nulla at felis ut justo egestas gravida. Aliquam non velit at lorem dictum sodales at at augue. Sed id justo at nisi ullamcorper eleifend a in risus. Donec dignissim libero id lacinia gravida. Integer porta justo vel odio sodales, sit amet facilisis sem volutpat.',
                'keyword1' => 'Sistem Informasi Kepegawaian',
                'keyword2' => 'Analisis',
                'keyword3' => 'Kepegawaian',
                'link_laporan' => 'drive.google.com',
                'tgl_verif_laporan' => '2024-04-14 00:00:00',
                'nilai' => 'A',
            ],

            [
                'nim' => '24060121100091',
                'nama' => 'Ella Ramirez',
                'periode_pkl' => '2023/2024 Ganjil',
                'instansi' => 'PT. ABC',
                'judul' => 'Pengembangan Aplikasi Manajemen Keuangan',
                'abstrak' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed at dui a nunc vestibulum ultricies. Nam condimentum lorem in tortor fermentum, at cursus justo ultricies. In hac habitasse platea dictumst. Nulla non purus arcu. Quisque auctor nulla id sapien mollis ultricies. Donec id elit ut magna euismod auctor. In eu tellus justo. Duis posuere mauris nec leo vestibulum malesuada. Nam eget augue ut leo aliquet egestas non id purus. Nam non luctus felis. Vivamus interdum hendrerit commodo. Nulla at felis ut justo egestas gravida. Aliquam non velit at lorem dictum sodales at at augue. Sed id justo at nisi ullamcorper eleifend a in risus. Donec dignissim libero id lacinia gravida. Integer porta justo vel odio sodales, sit amet facilisis sem volutpat.',
                'keyword1' => 'Aplikasi Manajemen Keuangan',
                'keyword2' => 'Pengembangan',
                'keyword3' => 'Keuangan',
                'link_laporan' => 'drive.google.com',
                'tgl_verif_laporan' => '2023-12-10 00:00:00',
                'nilai' => 'A',
            ],
            [
                'nim' => '24060121100092',
                'nama' => 'Samuel Evans',
                'periode_pkl' => '2023/2024 Ganjil',
                'instansi' => 'PT. XYZ',
                'judul' => 'Analisis Sistem Informasi Penjualan',
                'abstrak' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed at dui a nunc vestibulum ultricies. Nam condimentum lorem in tortor fermentum, at cursus justo ultricies. In hac habitasse platea dictumst. Nulla non purus arcu. Quisque auctor nulla id sapien mollis ultricies. Donec id elit ut magna euismod auctor. In eu tellus justo. Duis posuere mauris nec leo vestibulum malesuada. Nam eget augue ut leo aliquet egestas non id purus. Nam non luctus felis. Vivamus interdum hendrerit commodo. Nulla at felis ut justo egestas gravida. Aliquam non velit at lorem dictum sodales at at augue. Sed id justo at nisi ullamcorper eleifend a in risus. Donec dignissim libero id lacinia gravida. Integer porta justo vel odio sodales, sit amet facilisis sem volutpat.',
                'keyword1' => 'Sistem Informasi Penjualan',
                'keyword2' => 'Analisis',
                'keyword3' => 'Penjualan',
                'link_laporan' => 'drive.google.com',
                'tgl_verif_laporan' => '2023-12-10 00:00:00',
                'nilai' => 'B',
            ],
            [
                'nim' => '24060121100093',
                'nama' => 'Scarlett Coleman',
                'periode_pkl' => '2023/2024 Ganjil',
                'instansi' => 'PT. DEF',
                'judul' => 'Pengembangan Aplikasi Mobile Banking',
                'abstrak' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed at dui a nunc vestibulum ultricies. Nam condimentum lorem in tortor fermentum, at cursus justo ultricies. In hac habitasse platea dictumst. Nulla non purus arcu. Quisque auctor nulla id sapien mollis ultricies. Donec id elit ut magna euismod auctor. In eu tellus justo. Duis posuere mauris nec leo vestibulum malesuada. Nam eget augue ut leo aliquet egestas non id purus. Nam non luctus felis. Vivamus interdum hendrerit commodo. Nulla at felis ut justo egestas gravida. Aliquam non velit at lorem dictum sodales at at augue. Sed id justo at nisi ullamcorper eleifend a in risus. Donec dignissim libero id lacinia gravida. Integer porta justo vel odio sodales, sit amet facilisis sem volutpat.',
                'keyword1' => 'Aplikasi Mobile Banking',
                'keyword2' => 'Pengembangan',
                'keyword3' => 'Banking',
                'link_laporan' => 'drive.google.com',
                'tgl_verif_laporan' => '2023-12-10 00:00:00',
                'nilai' => 'C',
            ],
            [
                'nim' => '24060121100094',
                'nama' => 'Christopher Hayes',
                'periode_pkl' => '2023/2024 Ganjil',
                'instansi' => 'PT. GHI',
                'judul' => 'Pengembangan Sistem Informasi Geografis',
                'abstrak' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed at dui a nunc vestibulum ultricies. Nam condimentum lorem in tortor fermentum, at cursus justo ultricies. In hac habitasse platea dictumst. Nulla non purus arcu. Quisque auctor nulla id sapien mollis ultricies. Donec id elit ut magna euismod auctor. In eu tellus justo. Duis posuere mauris nec leo vestibulum malesuada. Nam eget augue ut leo aliquet egestas non id purus. Nam non luctus felis. Vivamus interdum hendrerit commodo. Nulla at felis ut justo egestas gravida. Aliquam non velit at lorem dictum sodales at at augue. Sed id justo at nisi ullamcorper eleifend a in risus. Donec dignissim libero id lacinia gravida. Integer porta justo vel odio sodales, sit amet facilisis sem volutpat.',
                'keyword1' => 'Sistem Informasi Geografis',
                'keyword2' => 'Pengembangan',
                'keyword3' => 'Geografis',
                'link_laporan' => 'drive.google.com',
                'tgl_verif_laporan' => '2023-12-10 00:00:00',
                'nilai' => 'A',
            ],
            [
                'nim' => '24060121100095',
                'nama' => 'Zoey Wood',
                'periode_pkl' => '2023/2024 Ganjil',
                'instansi' => 'PT. JKL',
                'judul' => 'Analisis dan Perancangan Sistem Informasi Persediaan',
                'abstrak' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed at dui a nunc vestibulum ultricies. Nam condimentum lorem in tortor fermentum, at cursus justo ultricies. In hac habitasse platea dictumst. Nulla non purus arcu. Quisque auctor nulla id sapien mollis ultricies. Donec id elit ut magna euismod auctor. In eu tellus justo. Duis posuere mauris nec leo vestibulum malesuada. Nam eget augue ut leo aliquet egestas non id purus. Nam non luctus felis. Vivamus interdum hendrerit commodo. Nulla at felis ut justo egestas gravida. Aliquam non velit at lorem dictum sodales at at augue. Sed id justo at nisi ullamcorper eleifend a in risus. Donec dignissim libero id lacinia gravida. Integer porta justo vel odio sodales, sit amet facilisis sem volutpat.',
                'keyword1' => 'Sistem Informasi Persediaan',
                'keyword2' => 'Analisis',
                'keyword3' => 'Persediaan',
                'link_laporan' => 'drive.google.com',
                'tgl_verif_laporan' => '2023-12-10 00:00:00',
                'nilai' => 'B',
            ],
            [
                'nim' => '24060121100096',
                'nama' => 'Nathan Ward',
                'periode_pkl' => '2023/2024 Ganjil',
                'instansi' => 'PT. MNO',
                'judul' => 'Pengembangan Aplikasi E-Learning',
                'abstrak' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed at dui a nunc vestibulum ultricies. Nam condimentum lorem in tortor fermentum, at cursus justo ultricies. In hac habitasse platea dictumst. Nulla non purus arcu. Quisque auctor nulla id sapien mollis ultricies. Donec id elit ut magna euismod auctor. In eu tellus justo. Duis posuere mauris nec leo vestibulum malesuada. Nam eget augue ut leo aliquet egestas non id purus. Nam non luctus felis. Vivamus interdum hendrerit commodo. Nulla at felis ut justo egestas gravida. Aliquam non velit at lorem dictum sodales at at augue. Sed id justo at nisi ullamcorper eleifend a in risus. Donec dignissim libero id lacinia gravida. Integer porta justo vel odio sodales, sit amet facilisis sem volutpat.',
                'keyword1' => 'Aplikasi E-Learning',
                'keyword2' => 'Pengembangan',
                'keyword3' => 'E-Learning',
                'link_laporan' => 'drive.google.com',
                'tgl_verif_laporan' => '2023-12-10 00:00:00',
                'nilai' => 'A',
            ],
            [
                'nim' => '24060121100097',
                'nama' => 'Hannah Torres',
                'periode_pkl' => '2023/2024 Ganjil',
                'instansi' => 'PT. PQR',
                'judul' => 'Analisis dan Perancangan Sistem Informasi Akademik',
                'abstrak' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed at dui a nunc vestibulum ultricies. Nam condimentum lorem in tortor fermentum, at cursus justo ultricies. In hac habitasse platea dictumst. Nulla non purus arcu. Quisque auctor nulla id sapien mollis ultricies. Donec id elit ut magna euismod auctor. In eu tellus justo. Duis posuere mauris nec leo vestibulum malesuada. Nam eget augue ut leo aliquet egestas non id purus. Nam non luctus felis. Vivamus interdum hendrerit commodo. Nulla at felis ut justo egestas gravida. Aliquam non velit at lorem dictum sodales at at augue. Sed id justo at nisi ullamcorper eleifend a in risus. Donec dignissim libero id lacinia gravida. Integer porta justo vel odio sodales, sit amet facilisis sem volutpat.',
                'keyword1' => 'Sistem Informasi Akademik',
                'keyword2' => 'Analisis',
                'keyword3' => 'Akademik',
                'link_laporan' => 'drive.google.com',
                'tgl_verif_laporan' => '2023-12-10 00:00:00',
                'nilai' => 'B',
            ],
            [
                'nim' => '24060121100098',
                'nama' => 'Andrew Russell',
                'periode_pkl' => '2023/2024 Ganjil',
                'instansi' => 'PT. STU',
                'judul' => 'Pengembangan Aplikasi Pencarian Tempat Wisata',
                'abstrak' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed at dui a nunc vestibulum ultricies. Nam condimentum lorem in tortor fermentum, at cursus justo ultricies. In hac habitasse platea dictumst. Nulla non purus arcu. Quisque auctor nulla id sapien mollis ultricies. Donec id elit ut magna euismod auctor. In eu tellus justo. Duis posuere mauris nec leo vestibulum malesuada. Nam eget augue ut leo aliquet egestas non id purus. Nam non luctus felis. Vivamus interdum hendrerit commodo. Nulla at felis ut justo egestas gravida. Aliquam non velit at lorem dictum sodales at at augue. Sed id justo at nisi ullamcorper eleifend a in risus. Donec dignissim libero id lacinia gravida. Integer porta justo vel odio sodales, sit amet facilisis sem volutpat.',
                'keyword1' => 'Aplikasi Pencarian Tempat Wisata',
                'keyword2' => 'Pengembangan',
                'keyword3' => 'Wisata',
                'link_laporan' => 'drive.google.com',
                'tgl_verif_laporan' => '2023-12-10 00:00:00',
                'nilai' => 'A',
            ],
            [
                'nim' => '24060121100099',
                'nama' => 'Brooklyn Barnes',
                'periode_pkl' => '2023/2024 Ganjil',
                'instansi' => 'PT. VWX',
                'judul' => 'Analisis dan Perancangan Sistem Informasi Manajemen Inventaris',
                'abstrak' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed at dui a nunc vestibulum ultricies. Nam condimentum lorem in tortor fermentum, at cursus justo ultricies. In hac habitasse platea dictumst. Nulla non purus arcu. Quisque auctor nulla id sapien mollis ultricies. Donec id elit ut magna euismod auctor. In eu tellus justo. Duis posuere mauris nec leo vestibulum malesuada. Nam eget augue ut leo aliquet egestas non id purus. Nam non luctus felis. Vivamus interdum hendrerit commodo. Nulla at felis ut justo egestas gravida. Aliquam non velit at lorem dictum sodales at at augue. Sed id justo at nisi ullamcorper eleifend a in risus. Donec dignissim libero id lacinia gravida. Integer porta justo vel odio sodales, sit amet facilisis sem volutpat.',
                'keyword1' => 'Sistem Informasi Manajemen Inventaris',
                'keyword2' => 'Analisis',
                'keyword3' => 'Inventaris',
                'link_laporan' => 'drive.google.com',
                'tgl_verif_laporan' => '2023-12-10 00:00:00',
                'nilai' => 'B',
            ],
            [
                'nim' => '24060121100100',
                'nama' => 'Isaac Hughes',
                'periode_pkl' => '2023/2024 Ganjil',
                'instansi' => 'PT. YZB',
                'judul' => 'Analisis dan Perancangan Sistem Informasi Kepegawaian',
                'abstrak' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed at dui a nunc vestibulum ultricies. Nam condimentum lorem in tortor fermentum, at cursus justo ultricies. In hac habitasse platea dictumst. Nulla non purus arcu. Quisque auctor nulla id sapien mollis ultricies. Donec id elit ut magna euismod auctor. In eu tellus justo. Duis posuere mauris nec leo vestibulum malesuada. Nam eget augue ut leo aliquet egestas non id purus. Nam non luctus felis. Vivamus interdum hendrerit commodo. Nulla at felis ut justo egestas gravida. Aliquam non velit at lorem dictum sodales at at augue. Sed id justo at nisi ullamcorper eleifend a in risus. Donec dignissim libero id lacinia gravida. Integer porta justo vel odio sodales, sit amet facilisis sem volutpat.',
                'keyword1' => 'Sistem Informasi Kepegawaian',
                'keyword2' => 'Analisis',
                'keyword3' => 'Kepegawaian',
                'link_laporan' => 'drive.google.com',
                'tgl_verif_laporan' => '2023-12-10 00:00:00',
                'nilai' => 'A',
            ],

     
        ];

        foreach ($arsip_pkl as $arsip) {
            ArsipPKL::create($arsip);
        }
    }
}
