<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CetakSKSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data_cetak_sk = [
            [
                'nim' => '24060121100071',
                'status' => 'Belum',
                'nama' => 'Abigail Gonzalez',
                'judul' => 'Pengembangan Aplikasi Manajemen Keuangan',
                'id_dospem' => 1,
                'tgl_mulai' => null,
                'tgl_selesai' => null,
                'tgl_verif_laporan' => '2024-04-16',
            ],
            [
                'nim' => '24060121100072',
                'status' => 'Belum',
                'nama' => 'Noah Lewis',
                'judul' => 'Analisis Sistem Informasi Penjualan',
                'id_dospem' => 2,
                'tgl_mulai' => null,
                'tgl_selesai' => null,
                'tgl_verif_laporan' => '2024-04-16',
            ],
            [
                'nim' => '24060121100073',
                'status' => 'Belum',
                'nama' => 'Emily Baker',
                'judul' => 'Pengembangan Aplikasi Mobile Banking',
                'id_dospem' => 3,
                'tgl_mulai' => null,
                'tgl_selesai' => null,
                'tgl_verif_laporan' => '2024-04-17',
            ],
            [
                'nim' => '24060121100074',
                'status' => 'Belum',
                'nama' => 'Samuel Harris',
                'judul' => 'Pengembangan Sistem Informasi Geografis',
                'id_dospem' => 4,
                'tgl_mulai' => null,
                'tgl_selesai' => null,
                'tgl_verif_laporan' => '2024-04-17',
            ],
            [
                'nim' => '24060121100075',
                'status' => 'Belum',
                'nama' => 'Elizabeth Young',
                'judul' => 'Analisis dan Perancangan Basis Data',
                'id_dospem' => 5,
                'tgl_mulai' => null,
                'tgl_selesai' => null,
                'tgl_verif_laporan' => '2024-04-18',
            ],
            [
                'nim' => '24060121100076',
                'status' => 'Belum',
                'nama' => 'David Scott',
                'judul' => 'Pembuatan Aplikasi Manajemen Proyek',
                'id_dospem' => 6,
                'tgl_mulai' => null,
                'tgl_selesai' => null,
                'tgl_verif_laporan' => '2024-04-18',
            ],
            [
                'nim' => '24060121100077',
                'status' => 'Belum',
                'nama' => 'Sofia Moore',
                'judul' => 'Pengembangan Aplikasi E-Commerce',
                'id_dospem' => 7,
                'tgl_mulai' => null,
                'tgl_selesai' => null,
                'tgl_verif_laporan' => '2024-04-19',
            ],
            [
                'nim' => '24060121100078',
                'status' => 'Belum',
                'nama' => 'Oliver Walker',
                'judul' => 'Analisis dan Perancangan Sistem Informasi Geografis',
                'id_dospem' => 8,
                'tgl_mulai' => null,
                'tgl_selesai' => null,
                'tgl_verif_laporan' => '2024-04-19',
            ],
            [
                'nim' => '24060121100079',
                'status' => 'Belum',
                'nama' => 'Victoria Rodriguez',
                'judul' => 'Pembuatan Aplikasi Mobile Learning',
                'id_dospem' => 9,
                'tgl_mulai' => null,
                'tgl_selesai' => null,
                'tgl_verif_laporan' => '2024-04-20',
            ],
            [
                'nim' => '24060121100080',
                'status' => 'Belum',
                'nama' => 'Lucas Martin',
                'judul' => 'Analisis dan Perancangan Sistem Informasi Keuangan',
                'id_dospem' => 10,
                'tgl_mulai' => null,
                'tgl_selesai' => null,
                'tgl_verif_laporan' => '2024-04-20',
            ],

            [
                'nim' => '24060121100081',
                'status' => 'Belum',
                'nama' => 'Grace Nguyen',
                'judul' => 'Pengembangan Aplikasi Manajemen Keuangan',
                'id_dospem' => 1,
                'tgl_mulai' => null,
                'tgl_selesai' => null,
                'tgl_verif_laporan' => '2024-04-10',
            ],
            [
                'nim' => '24060121100082',
                'status' => 'Belum',
                'nama' => 'Logan King',
                'judul' => 'Analisis Sistem Informasi Penjualan',
                'id_dospem' => 1,
                'tgl_mulai' => null,
                'tgl_selesai' => null,
                'tgl_verif_laporan' => '2024-04-10',
            ],
            [
                'nim' => '24060121100083',
                'status' => 'Belum',
                'nama' => 'Aria Chavez',
                'judul' => 'Pengembangan Aplikasi Mobile Banking',
                'id_dospem' => 2,
                'tgl_mulai' => null,
                'tgl_selesai' => null,
                'tgl_verif_laporan' => '2024-04-11',
            ],
            [
                'nim' => '24060121100084',
                'status' => 'Belum',
                'nama' => 'Jackson Green',
                'judul' => 'Pengembangan Sistem Informasi Geografis',
                'id_dospem' => 2,
                'tgl_mulai' => null,
                'tgl_selesai' => null,
                'tgl_verif_laporan' => '2024-04-11',
            ],
            [
                'nim' => '24060121100085',
                'status' => 'Belum',
                'nama' => 'Lily Rivera',
                'judul' => 'Analisis dan Perancangan Sistem Informasi Persediaan',
                'id_dospem' => 3,
                'tgl_mulai' => null,
                'tgl_selesai' => null,
                'tgl_verif_laporan' => '2024-04-12',
            ],
            [
                'nim' => '24060121100086',
                'status' => 'Belum',
                'nama' => 'Gabriel Adams',
                'judul' => 'Pengembangan Aplikasi E-Learning',
                'id_dospem' => 3,
                'tgl_mulai' => null,
                'tgl_selesai' => null,
                'tgl_verif_laporan' => '2024-04-12',
            ],
            [
                'nim' => '24060121100087',
                'status' => 'Belum',
                'nama' => 'Addison Mitchell',
                'judul' => 'Analisis dan Perancangan Sistem Informasi Akademik',
                'id_dospem' => 4,
                'tgl_mulai' => null,
                'tgl_selesai' => null,
                'tgl_verif_laporan' => '2024-04-13',
            ],
            [
                'nim' => '24060121100088',
                'status' => 'Belum',
                'nama' => 'Ryan Hill',
                'judul' => 'Pengembangan Aplikasi Pencarian Tempat Wisata',
                'id_dospem' => 4,
                'tgl_mulai' => null,
                'tgl_selesai' => null,
                'tgl_verif_laporan' => '2024-04-13',
            ],
            [
                'nim' => '24060121100089',
                'status' => 'Belum',
                'nama' => 'Natalie Carter',
                'judul' => 'Analisis dan Perancangan Sistem Informasi Manajemen Inventaris',
                'id_dospem' => 5,
                'tgl_mulai' => null,
                'tgl_selesai' => null,
                'tgl_verif_laporan' => '2024-04-14',
            ],
            [
                'nim' => '24060121100090',
                'status' => 'Belum',
                'nama' => 'John Nelson',
                'judul' => 'Analisis dan Perancangan Sistem Informasi Kepegawaian',
                'id_dospem' => 5,
                'tgl_mulai' => null,
                'tgl_selesai' => null,
                'tgl_verif_laporan' => '2024-04-14',
            ],

            [
                'nim' => '24060121100091',
                'status' => 'Sudah',
                'nama' => 'Ella Ramirez',
                'judul' => 'Pengembangan Aplikasi Manajemen Keuangan',
                'id_dospem' => 1,
                'tgl_mulai' => "2023-08-15",
                'tgl_selesai' => "2024-01-15",
                'tgl_verif_laporan' => '2023-12-10',
            ],
            [
                'nim' => '24060121100092',
                'status' => 'Sudah',
                'nama' => 'Samuel Evans',
                'judul' => 'Analisis Sistem Informasi Penjualan',
                'id_dospem' => 1,
                'tgl_mulai' => "2023-08-15",
                'tgl_selesai' => "2024-01-15",
                'tgl_verif_laporan' => '2023-12-10',
            ],
            [
                'nim' => '24060121100093',
                'status' => 'Sudah',
                'nama' => 'Scarlett Coleman',
                'judul' => 'Pengembangan Aplikasi Mobile Banking',
                'id_dospem' => 2,
                'tgl_mulai' => "2023-08-15",
                'tgl_selesai' => "2024-01-15",
                'tgl_verif_laporan' => '2023-12-10',
            ],
            [
                'nim' => '24060121100094',
                'status' => 'Sudah',
                'nama' => 'Christopher Hayes',
                'judul' => 'Pengembangan Sistem Informasi Geografis',
                'id_dospem' => 2,
                'tgl_mulai' => "2023-08-15",
                'tgl_selesai' => "2024-01-15",
                'tgl_verif_laporan' => '2023-12-10',
            ],
            [
                'nim' => '24060121100095',
                'status' => 'Sudah',
                'nama' => 'Zoey Wood',
                'judul' => 'Analisis dan Perancangan Sistem Informasi Persediaan',
                'id_dospem' => 3,
                'tgl_mulai' => "2023-08-15",
                'tgl_selesai' => "2024-01-15",
                'tgl_verif_laporan' => '2023-12-10',
            ],
            [
                'nim' => '24060121100096',
                'status' => 'Sudah',
                'nama' => 'Nathan Ward',
                'judul' => 'Pengembangan Aplikasi E-Learning',
                'id_dospem' => 3,
                'tgl_mulai' => "2023-08-15",
                'tgl_selesai' => "2024-01-15",
                'tgl_verif_laporan' => '2023-12-10',
            ],
            [
                'nim' => '24060121100097',
                'status' => 'Sudah',
                'nama' => 'Hannah Torres',
                'judul' => 'Analisis dan Perancangan Sistem Informasi Akademik',
                'id_dospem' => 4,
                'tgl_mulai' => "2023-08-15",
                'tgl_selesai' => "2024-01-15",
                'tgl_verif_laporan' => '2023-12-10',
            ],
            [
                'nim' => '24060121100098',
                'status' => 'Sudah',
                'nama' => 'Andrew Russell',
                'judul' => 'Pengembangan Aplikasi Pencarian Tempat Wisata',
                'id_dospem' => 4,
                'tgl_mulai' => "2023-08-15",
                'tgl_selesai' => "2024-01-15",
                'tgl_verif_laporan' => '2023-12-10',
            ],
            [
                'nim' => '24060121100099',
                'status' => 'Sudah',
                'nama' => 'Brooklyn Barnes',
                'judul' => 'Analisis dan Perancangan Sistem Informasi Manajemen Inventaris',
                'id_dospem' => 5,
                'tgl_mulai' => "2023-08-15",
                'tgl_selesai' => "2024-01-15",
                'tgl_verif_laporan' => '2023-12-10',
            ],
            [
                'nim' => '24060121100100',
                'status' => 'Sudah',
                'nama' => 'Isaac Hughes',
                'judul' => 'Analisis dan Perancangan Sistem Informasi Kepegawaian',
                'id_dospem' => 5,
                'tgl_mulai' => "2023-08-15",
                'tgl_selesai' => "2024-01-15",
                'tgl_verif_laporan' => '2023-12-10',
            ],



            [
                'nim' => '24060121160001',
                'status' => 'Sudah',
                'nama' => 'Mahasiswa 1',
                'judul' => 'Sistem Informasi Penjualan',
                'id_dospem' => 1,
                'tgl_mulai' => "2023-01-15",
                'tgl_selesai' => "2023-08-14",
                'tgl_verif_laporan' => '2023-08-10',
            ],
            [
                'nim' => '24060121160002',
                'status' => 'Sudah',
                'nama' => 'Mahasiswa 2',
                'judul' => 'Sistem Informasi Keuangan',
                'id_dospem' => 1,
                'tgl_mulai' => "2023-01-15",
                'tgl_selesai' => "2023-08-14",
                'tgl_verif_laporan' => '2023-08-10',
            ],
            [
                'nim' => '24060121160003',
                'status' => 'Sudah',
                'nama' => 'Mahasiswa 3',
                'judul' => 'Sistem Informasi Akademik',
                'id_dospem' => 1,
                'tgl_mulai' => "2023-01-15",
                'tgl_selesai' => "2023-08-14",
                'tgl_verif_laporan' => '2023-08-10',
            ],
            [
                'nim' => '24060121160004',
                'status' => 'Sudah',
                'nama' => 'Mahasiswa 4',
                'judul' => 'Sistem Informasi Inventaris',
                'id_dospem' => 2,
                'tgl_mulai' => "2023-01-15",
                'tgl_selesai' => "2023-08-14",
                'tgl_verif_laporan' => '2023-08-10',
            ],
            [
                'nim' => '24060121160005',
                'status' => 'Sudah',
                'nama' => 'Mahasiswa 5',
                'judul' => 'Sistem Informasi Perpustakaan',
                'id_dospem' => 2,
                'tgl_mulai' => "2023-01-15",
                'tgl_selesai' => "2023-08-14",
                'tgl_verif_laporan' => '2023-08-10',
            ],
            [
                'nim' => '24060121160006',
                'status' => 'Sudah',
                'nama' => 'Mahasiswa 6',
                'judul' => 'Sistem Informasi Kepegawaian',
                'id_dospem' => 2,
                'tgl_mulai' => "2023-01-15",
                'tgl_selesai' => "2023-08-14",
                'tgl_verif_laporan' => '2023-08-10',
            ],
            [
                'nim' => '24060121160007',
                'status' => 'Sudah',
                'nama' => 'Mahasiswa 7',
                'judul' => 'Sistem Informasi Perbankan',
                'id_dospem' => 3,
                'tgl_mulai' => "2023-01-15",
                'tgl_selesai' => "2023-08-14",
                'tgl_verif_laporan' => '2023-08-10',
            ],
            [
                'nim' => '24060121160008',
                'status' => 'Sudah',
                'nama' => 'Mahasiswa 8',
                'judul' => 'Sistem Informasi Pergudangan',
                'id_dospem' => 3,
                'tgl_mulai' => "2023-01-15",
                'tgl_selesai' => "2023-08-14",
                'tgl_verif_laporan' => '2023-08-10',
            ],
            [
                'nim' => '24060121160009',
                'status' => 'Sudah',
                'nama' => 'Mahasiswa 9',
                'judul' => 'Sistem Informasi Pemerintahan',
                'id_dospem' => 4,
                'tgl_mulai' => "2023-01-15",
                'tgl_selesai' => "2023-08-14",
                'tgl_verif_laporan' => '2023-08-10',
            ],
            [
                'nim' => '24060121160010',
                'status' => 'Sudah',
                'nama' => 'Mahasiswa 10',
                'judul' => 'Sistem Informasi Pendidikan',
                'id_dospem' => 4,
                'tgl_mulai' => "2023-01-15",
                'tgl_selesai' => "2023-08-14",
                'tgl_verif_laporan' => '2023-08-10',
            ],
            
            [
                'nim' => '24060121160011',
                'status' => 'Sudah',
                'nama' => 'Mahasiswa 11',
                'judul' => 'Sistem Informasi Kesehatan',
                'id_dospem' => 1,
                'tgl_mulai' => "2022-08-15",
                'tgl_selesai' => "2023-01-14",
                'tgl_verif_laporan' => '2023-01-10',
            ],
            [
                'nim' => '24060121160012',
                'status' => 'Sudah',
                'nama' => 'Mahasiswa 12',
                'judul' => 'Sistem Informasi Perhotelan',
                'id_dospem' => 1,
                'tgl_mulai' => "2022-08-15",
                'tgl_selesai' => "2023-01-14",
                'tgl_verif_laporan' => '2023-01-10',
            ],
            [
                'nim' => '24060121160013',
                'status' => 'Sudah',
                'nama' => 'Mahasiswa 13',
                'judul' => 'Sistem Informasi Pariwisata',
                'id_dospem' => 1,
                'tgl_mulai' => "2022-08-15",
                'tgl_selesai' => "2023-01-14",
                'tgl_verif_laporan' => '2023-01-10',
            ],
            [
                'nim' => '24060121160014',
                'status' => 'Sudah',
                'nama' => 'Mahasiswa 14',
                'judul' => 'Sistem Informasi Transportasi',
                'id_dospem' => 2,
                'tgl_mulai' => "2022-08-15",
                'tgl_selesai' => "2023-01-14",
                'tgl_verif_laporan' => '2023-01-10',
            ],
            [
                'nim' => '24060121160015',
                'status' => 'Sudah',
                'nama' => 'Mahasiswa 15',
                'judul' => 'Sistem Informasi Pertanian',
                'id_dospem' => 2,
                'tgl_mulai' => "2022-08-15",
                'tgl_selesai' => "2023-01-14",
                'tgl_verif_laporan' => '2023-01-10',
            ],
            [
                'nim' => '24060121160016',
                'status' => 'Sudah',
                'nama' => 'Mahasiswa 16',
                'judul' => 'Sistem Informasi Peternakan',
                'id_dospem' => 2,
                'tgl_mulai' => "2022-08-15",
                'tgl_selesai' => "2023-01-14",
                'tgl_verif_laporan' => '2023-01-10',
            ],
            [
                'nim' => '24060121160017',
                'status' => 'Sudah',
                'nama' => 'Mahasiswa 17',
                'judul' => 'Sistem Informasi Perikanan',
                'id_dospem' => 3,
                'tgl_mulai' => "2022-08-15",
                'tgl_selesai' => "2023-01-14",
                'tgl_verif_laporan' => '2023-01-10',
            ],
            [
                'nim' => '24060121160018',
                'status' => 'Sudah',
                'nama' => 'Mahasiswa 18',
                'judul' => 'Sistem Informasi Kehutanan',
                'id_dospem' => 3,
                'tgl_mulai' => "2022-08-15",
                'tgl_selesai' => "2023-01-14",
                'tgl_verif_laporan' => '2023-01-10',
            ],
            [
                'nim' => '24060121160019',
                'status' => 'Sudah',
                'nama' => 'Mahasiswa 19',
                'judul' => 'Sistem Informasi Kelautan',
                'id_dospem' => 4,
                'tgl_mulai' => "2022-08-15",
                'tgl_selesai' => "2023-01-14",
                'tgl_verif_laporan' => '2023-01-10',
            ],
            [
                'nim' => '24060121160020',
                'status' => 'Sudah',
                'nama' => 'Mahasiswa 20',
                'judul' => 'Sistem Informasi Energi',
                'id_dospem' => 4,
                'tgl_mulai' => "2022-08-15",
                'tgl_selesai' => "2023-01-14",
                'tgl_verif_laporan' => '2023-01-10',
            ]
            
        ];

        foreach ($data_cetak_sk as $cetak_sk) {
            \App\Models\CetakSK::create($cetak_sk);
        }
    }
}
