<?php

namespace Database\Seeders;

use App\Models\PKL;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class PKLSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $pkl = [
            [
                'nim' => '24060121100011',
                'status' => 'Praregistrasi',
                'instansi' => 'PT. ABC',
                'judul' => 'Pengembangan Sistem Informasi',
            ],
            [
                'nim' => '24060121100012',
                'status' => 'Praregistrasi',
                'instansi' => 'PT. XYZ',
                'judul' => 'Analisis Data Penjualan',
            ],
            [
                'nim' => '24060121100013',
                'status' => 'Praregistrasi',
                'instansi' => 'PT. QWE',
                'judul' => 'Pembuatan Aplikasi Mobile',
            ],
            [
                'nim' => '24060121100014',
                'status' => 'Praregistrasi',
                'instansi' => 'PT. RST',
                'judul' => 'Pengembangan Website E-commerce',
            ],
            [
                'nim' => '24060121100015',
                'status' => 'Praregistrasi',
                'instansi' => 'PT. UVW',
                'judul' => 'Pembuatan Sistem Keamanan Jaringan',
            ],
            [
                'nim' => '24060121100016',
                'status' => 'Praregistrasi',
                'instansi' => 'PT. JKL',
                'judul' => 'Analisis Kebutuhan Perangkat Lunak',
            ],
            [
                'nim' => '24060121100017',
                'status' => 'Praregistrasi',
                'instansi' => 'PT. MNO',
                'judul' => 'Pengembangan Aplikasi Penjualan Online',
            ],
            [
                'nim' => '24060121100018',
                'status' => 'Praregistrasi',
                'instansi' => 'PT. GHI',
                'judul' => 'Pembuatan Sistem Informasi Manajemen',
            ],
            [
                'nim' => '24060121100019',
                'status' => 'Praregistrasi',
                'instansi' => 'PT. DEF',
                'judul' => 'Analisis Keamanan Aplikasi Web',
            ],
            [
                'nim' => '24060121100020',
                'status' => 'Praregistrasi',
                'instansi' => 'PT. STU',
                'judul' => 'Pengembangan Aplikasi Mobile Learning',
            ],
            [
                'nim' => '24060121100021',
                'status' => 'Registrasi',
                'instansi' => 'PT. IJK',
                'judul' => 'Implementasi Teknologi IoT dalam Industri',
                'scan_irs' => '/private/template/scan_irs_example.jpg',
                'tgl_registrasi' => '2024-08-10',
            ],
            [
                'nim' => '24060121100022',
                'status' => 'Registrasi',
                'instansi' => 'PT. LMN',
                'judul' => 'Pembuatan Aplikasi E-learning',
                'scan_irs' => '/private/template/scan_irs_example.jpg',
                'tgl_registrasi' => '2024-08-10',
            ],
            [
                'nim' => '24060121100023',
                'status' => 'Registrasi',
                'instansi' => 'PT. OPQ',
                'judul' => 'Analisis Sistem Manajemen Basis Data',
                'scan_irs' => '/private/template/scan_irs_example.jpg',
                'tgl_registrasi' => '2024-08-10',
            ],
            [
                'nim' => '24060121100024',
                'status' => 'Registrasi',
                'instansi' => 'PT. RUV',
                'judul' => 'Pengembangan Sistem Keuangan Berbasis Teknologi',
                'scan_irs' => '/private/template/scan_irs_example.jpg',
                'tgl_registrasi' => '2024-08-10',
            ],
            [
                'nim' => '24060121100025',
                'status' => 'Registrasi',
                'instansi' => 'PT. WXY',
                'judul' => 'Pembuatan Aplikasi Monitoring Lingkungan',
                'scan_irs' => '/private/template/scan_irs_example.jpg',
                'tgl_registrasi' => '2024-08-10',
            ],

            [
                'nim' => '24060121100026',
                'status' => 'Aktif',
                'instansi' => 'PT. XYZ',
                'judul' => 'Pengembangan Aplikasi Manajemen Keuangan',
                'scan_irs' => '/private/template/scan_irs_example.jpg',
                'tgl_registrasi' => '2024-08-01',
            ],
            [
                'nim' => '24060121100027',
                'status' => 'Aktif',
                'instansi' => 'PT. ABC',
                'judul' => 'Analisis Sistem Informasi Penjualan',
                'scan_irs' => '/private/template/scan_irs_example.jpg',
                'tgl_registrasi' => '2024-08-01',
            ],
            [
                'nim' => '24060121100028',
                'status' => 'Aktif',
                'instansi' => 'PT. DEF',
                'judul' => 'Pembuatan Aplikasi Mobile Banking',
                'scan_irs' => '/private/template/scan_irs_example.jpg',
                'tgl_registrasi' => '2024-08-01',
            ],
            [
                'nim' => '24060121100029',
                'status' => 'Aktif',
                'instansi' => 'PT. GHI',
                'judul' => 'Pengembangan Sistem Informasi Geografis',
                'scan_irs' => '/private/template/scan_irs_example.jpg',
                'tgl_registrasi' => '2024-08-01',
            ],
            [
                'nim' => '24060121100030',
                'status' => 'Aktif',
                'instansi' => 'PT. JKL',
                'judul' => 'Analisis Keamanan Jaringan Komputer',
                'scan_irs' => '/private/template/scan_irs_example.jpg',
                'tgl_registrasi' => '2024-01-15', // tidak lulus periode sebelumnya
            ],

            [
                'nim' => '24060121100031',
                'status' => 'Aktif',
                'instansi' => 'PT. MNO',
                'judul' => 'Pengembangan Sistem Informasi Akademik',
                'scan_irs' => '/private/template/scan_irs_example.jpg',
                'tgl_registrasi' => '2024-08-01',
            ],
            [
                'nim' => '24060121100032',
                'status' => 'Aktif',
                'instansi' => 'PT. PQR',
                'judul' => 'Analisis Kebutuhan Pengguna Aplikasi',
                'scan_irs' => '/private/template/scan_irs_example.jpg',
                'tgl_registrasi' => '2024-08-01',
            ],
            [
                'nim' => '24060121100033',
                'status' => 'Aktif',
                'instansi' => 'PT. STU',
                'judul' => 'Pembuatan Sistem Informasi Manajemen Proyek',
                'scan_irs' => '/private/template/scan_irs_example.jpg',
                'tgl_registrasi' => '2024-08-01',
            ],
            [
                'nim' => '24060121100034',
                'status' => 'Aktif',
                'instansi' => 'PT. UVW',
                'judul' => 'Pengembangan Aplikasi Penjualan Online',
                'scan_irs' => '/private/template/scan_irs_example.jpg',
                'tgl_registrasi' => '2024-08-01',
            ],
            [
                'nim' => '24060121100035',
                'status' => 'Aktif',
                'instansi' => 'PT. XYZ',
                'judul' => 'Analisis Keamanan Sistem Informasi',
                'scan_irs' => '/private/template/scan_irs_example.jpg',
                'tgl_registrasi' => '2024-08-01',
            ],
            [
                'nim' => '24060121100036',
                'status' => 'Aktif',
                'instansi' => 'PT. ABC',
                'judul' => 'Pembuatan Aplikasi Android',
                'scan_irs' => '/private/template/scan_irs_example.jpg',
                'tgl_registrasi' => '2024-08-01',
            ],
            [
                'nim' => '24060121100037',
                'status' => 'Aktif',
                'instansi' => 'PT. DEF',
                'judul' => 'Pengembangan Sistem Informasi Geografis',
                'scan_irs' => '/private/template/scan_irs_example.jpg',
                'tgl_registrasi' => '2024-08-01',
            ],
            [
                'nim' => '24060121100038',
                'status' => 'Aktif',
                'instansi' => 'PT. GHI',
                'judul' => 'Analisis dan Perancangan Basis Data',
                'scan_irs' => '/private/template/scan_irs_example.jpg',
                'tgl_registrasi' => '2024-08-01',
            ],
            [
                'nim' => '24060121100039',
                'status' => 'Aktif',
                'instansi' => 'PT. JKL',
                'judul' => 'Pengembangan Aplikasi E-commerce',
                'scan_irs' => '/private/template/scan_irs_example.jpg',
                'tgl_registrasi' => '2024-08-01',
            ],
            [
                'nim' => '24060121100040',
                'status' => 'Aktif',
                'instansi' => 'PT. MNO',
                'judul' => 'Analisis dan Perancangan Sistem Informasi',
                'scan_irs' => '/private/template/scan_irs_example.jpg',
                'tgl_registrasi' => '2024-01-15', // tidak lulus periode sebelumnya
            ],

            [
                'nim' => '24060121100041',
                'status' => 'Aktif',
                'instansi' => 'PT. ABC',
                'judul' => 'Pembuatan Aplikasi Manajemen Keuangan',
                'scan_irs' => '/private/template/scan_irs_example.jpg',
                'tgl_registrasi' => '2024-08-01',
            ],
            [
                'nim' => '24060121100042',
                'status' => 'Aktif',
                'instansi' => 'PT. XYZ',
                'judul' => 'Analisis Sistem Informasi Penjualan',
                'scan_irs' => '/private/template/scan_irs_example.jpg',
                'tgl_registrasi' => '2024-08-01',
            ],
            [
                'nim' => '24060121100043',
                'status' => 'Aktif',
                'instansi' => 'PT. DEF',
                'judul' => 'Pengembangan Aplikasi Mobile Banking',
                'scan_irs' => '/private/template/scan_irs_example.jpg',
                'tgl_registrasi' => '2024-08-01',
            ],
            [
                'nim' => '24060121100044',
                'status' => 'Aktif',
                'instansi' => 'PT. GHI',
                'judul' => 'Pengembangan Sistem Informasi Geografis',
                'scan_irs' => '/private/template/scan_irs_example.jpg',
                'tgl_registrasi' => '2024-08-01',
            ],
            [
                'nim' => '24060121100045',
                'status' => 'Aktif',
                'instansi' => 'PT. JKL',
                'judul' => 'Analisis Keamanan Jaringan Komputer',
                'scan_irs' => '/private/template/scan_irs_example.jpg',
                'tgl_registrasi' => '2024-08-01',
            ],
            [
                'nim' => '24060121100046',
                'status' => 'Aktif',
                'instansi' => 'PT. MNO',
                'judul' => 'Pengembangan Aplikasi Monitoring Lingkungan',
                'scan_irs' => '/private/template/scan_irs_example.jpg',
                'tgl_registrasi' => '2024-08-01',
            ],
            [
                'nim' => '24060121100047',
                'status' => 'Aktif',
                'instansi' => 'PT. PQR',
                'judul' => 'Pembuatan Sistem Informasi Manajemen Proyek',
                'scan_irs' => '/private/template/scan_irs_example.jpg',
                'tgl_registrasi' => '2024-08-01',
            ],
            [
                'nim' => '24060121100048',
                'status' => 'Aktif',
                'instansi' => 'PT. STU',
                'judul' => 'Analisis dan Perancangan Basis Data',
                'scan_irs' => '/private/template/scan_irs_example.jpg',
                'tgl_registrasi' => '2024-08-01',
            ],
            [
                'nim' => '24060121100049',
                'status' => 'Aktif',
                'instansi' => 'PT. UVW',
                'judul' => 'Pembuatan Aplikasi Android',
                'scan_irs' => '/private/template/scan_irs_example.jpg',
                'tgl_registrasi' => '2024-08-01',
            ],
            [
                'nim' => '24060121100050',
                'status' => 'Aktif',
                'instansi' => 'PT. WXY',
                'judul' => 'Analisis dan Perancangan Sistem Informasi',
                'scan_irs' => '/private/template/scan_irs_example.jpg',
                'tgl_registrasi' => '2024-08-01',
            ],

            [
                'nim' => '24060121100051',
                'status' => 'Aktif',
                'instansi' => 'PT. ABC',
                'judul' => 'Pengembangan Aplikasi Manajemen Keuangan',
                'scan_irs' => '/private/template/scan_irs_example.jpg',
                'tgl_registrasi' => '2024-08-01',
            ],
            [
                'nim' => '24060121100052',
                'status' => 'Aktif',
                'instansi' => 'PT. XYZ',
                'judul' => 'Analisis Sistem Informasi Penjualan',
                'scan_irs' => '/private/template/scan_irs_example.jpg',
                'tgl_registrasi' => '2024-08-01',
            ],
            [
                'nim' => '24060121100053',
                'status' => 'Aktif',
                'instansi' => 'PT. DEF',
                'judul' => 'Pengembangan Aplikasi Mobile Banking',
                'scan_irs' => '/private/template/scan_irs_example.jpg',
                'tgl_registrasi' => '2024-08-01',
            ],
            [
                'nim' => '24060121100054',
                'status' => 'Aktif',
                'instansi' => 'PT. GHI',
                'judul' => 'Pengembangan Sistem Informasi Geografis',
                'scan_irs' => '/private/template/scan_irs_example.jpg',
                'tgl_registrasi' => '2024-08-01',
            ],
            [
                'nim' => '24060121100055',
                'status' => 'Aktif',
                'instansi' => 'PT. JKL',
                'judul' => 'Analisis Keamanan Jaringan Komputer',
                'scan_irs' => '/private/template/scan_irs_example.jpg',
                'tgl_registrasi' => '2024-08-01',
            ],
            [
                'nim' => '24060121100056',
                'status' => 'Aktif',
                'instansi' => 'PT. MNO',
                'judul' => 'Pengembangan Aplikasi Monitoring Lingkungan',
                'scan_irs' => '/private/template/scan_irs_example.jpg',
                'tgl_registrasi' => '2024-08-01',
            ],
            [
                'nim' => '24060121100057',
                'status' => 'Aktif',
                'instansi' => 'PT. PQR',
                'judul' => 'Pembuatan Sistem Informasi Manajemen Proyek',
                'scan_irs' => '/private/template/scan_irs_example.jpg',
                'tgl_registrasi' => '2024-08-01',
            ],
            [
                'nim' => '24060121100058',
                'status' => 'Aktif',
                'instansi' => 'PT. STU',
                'judul' => 'Analisis dan Perancangan Basis Data',
                'scan_irs' => '/private/template/scan_irs_example.jpg',
                'tgl_registrasi' => '2024-08-01',
            ],
            [
                'nim' => '24060121100059',
                'status' => 'Aktif',
                'instansi' => 'PT. UVW',
                'judul' => 'Pembuatan Aplikasi Android',
                'scan_irs' => '/private/template/scan_irs_example.jpg',
                'tgl_registrasi' => '2024-08-01',
            ],
            [
                'nim' => '24060121100060',
                'status' => 'Aktif',
                'instansi' => 'PT. WXY',
                'judul' => 'Analisis dan Perancangan Sistem Informasi',
                'scan_irs' => '/private/template/scan_irs_example.jpg',
                'tgl_registrasi' => '2024-08-01',
            ],

            [
                'nim' => '24060121100061',
                'status' => 'Laporan',
                'instansi' => 'PT. ABC',
                'judul' => 'Pengembangan Aplikasi Manajemen Keuangan',
                'scan_irs' => '/private/template/scan_irs_example.jpg',
                'tgl_registrasi' => '2024-08-01',
                'abstrak' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed at dui a nunc vestibulum ultricies. Nam condimentum lorem in tortor fermentum, at cursus justo ultricies. In hac habitasse platea dictumst. Nulla non purus arcu. Quisque auctor nulla id sapien mollis ultricies. Donec id elit ut magna euismod auctor. In eu tellus justo. Duis posuere mauris nec leo vestibulum malesuada. Nam eget augue ut leo aliquet egestas non id purus. Nam non luctus felis. Vivamus interdum hendrerit commodo. Nulla at felis ut justo egestas gravida. Aliquam non velit at lorem dictum sodales at at augue. Sed id justo at nisi ullamcorper eleifend a in risus. Donec dignissim libero id lacinia gravida. Integer porta justo vel odio sodales, sit amet facilisis sem volutpat.',
                'keyword1' => 'Aplikasi Manajemen Keuangan',
                'keyword2' => 'Pengembangan',
                'keyword3' => 'Keuangan',
                'link_berkas' => 'drive.google.com',
                'tgl_laporan' => '2024-09-01',
            ],
            [
                'nim' => '24060121100062',
                'status' => 'Laporan',
                'instansi' => 'PT. XYZ',
                'judul' => 'Analisis Sistem Informasi Penjualan',
                'scan_irs' => '/private/template/scan_irs_example.jpg',
                'tgl_registrasi' => '2024-08-01',
                'abstrak' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed at dui a nunc vestibulum ultricies. Nam condimentum lorem in tortor fermentum, at cursus justo ultricies. In hac habitasse platea dictumst. Nulla non purus arcu. Quisque auctor nulla id sapien mollis ultricies. Donec id elit ut magna euismod auctor. In eu tellus justo. Duis posuere mauris nec leo vestibulum malesuada. Nam eget augue ut leo aliquet egestas non id purus. Nam non luctus felis. Vivamus interdum hendrerit commodo. Nulla at felis ut justo egestas gravida. Aliquam non velit at lorem dictum sodales at at augue. Sed id justo at nisi ullamcorper eleifend a in risus. Donec dignissim libero id lacinia gravida. Integer porta justo vel odio sodales, sit amet facilisis sem volutpat.',
                'keyword1' => 'Sistem Informasi Penjualan',
                'keyword2' => 'Analisis',
                'keyword3' => 'Penjualan',
                'link_berkas' => 'drive.google.com',
                'tgl_laporan' => '2024-09-01',
            ],
            [
                'nim' => '24060121100063',
                'status' => 'Laporan',
                'instansi' => 'PT. DEF',
                'judul' => 'Pengembangan Aplikasi Mobile Banking',
                'scan_irs' => '/private/template/scan_irs_example.jpg',
                'tgl_registrasi' => '2024-08-01',
                'abstrak' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed at dui a nunc vestibulum ultricies. Nam condimentum lorem in tortor fermentum, at cursus justo ultricies. In hac habitasse platea dictumst. Nulla non purus arcu. Quisque auctor nulla id sapien mollis ultricies. Donec id elit ut magna euismod auctor. In eu tellus justo. Duis posuere mauris nec leo vestibulum malesuada. Nam eget augue ut leo aliquet egestas non id purus. Nam non luctus felis. Vivamus interdum hendrerit commodo. Nulla at felis ut justo egestas gravida. Aliquam non velit at lorem dictum sodales at at augue. Sed id justo at nisi ullamcorper eleifend a in risus. Donec dignissim libero id lacinia gravida. Integer porta justo vel odio sodales, sit amet facilisis sem volutpat.',
                'keyword1' => 'Aplikasi Mobile Banking',
                'keyword2' => 'Pengembangan',
                'keyword3' => 'Banking',
                'link_berkas' => 'drive.google.com',
                'tgl_laporan' => '2024-09-01',
            ],
            [
                'nim' => '24060121100064',
                'status' => 'Laporan',
                'instansi' => 'PT. GHI',
                'judul' => 'Pengembangan Sistem Informasi Geografis',
                'scan_irs' => '/private/template/scan_irs_example.jpg',
                'tgl_registrasi' => '2024-08-01',
                'abstrak' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed at dui a nunc vestibulum ultricies. Nam condimentum lorem in tortor fermentum, at cursus justo ultricies. In hac habitasse platea dictumst. Nulla non purus arcu. Quisque auctor nulla id sapien mollis ultricies. Donec id elit ut magna euismod auctor. In eu tellus justo. Duis posuere mauris nec leo vestibulum malesuada. Nam eget augue ut leo aliquet egestas non id purus. Nam non luctus felis. Vivamus interdum hendrerit commodo. Nulla at felis ut justo egestas gravida. Aliquam non velit at lorem dictum sodales at at augue. Sed id justo at nisi ullamcorper eleifend a in risus. Donec dignissim libero id lacinia gravida. Integer porta justo vel odio sodales, sit amet facilisis sem volutpat.',
                'keyword1' => 'Sistem Informasi Geografis',
                'keyword2' => 'Pengembangan',
                'keyword3' => 'Geografis',
                'link_berkas' => 'drive.google.com',
                'tgl_laporan' => '2024-09-01',
            ],
            [
                'nim' => '24060121100065',
                'status' => 'Laporan',
                'instansi' => 'PT. JKL',
                'judul' => 'Analisis Keamanan Jaringan Komputer',
                'scan_irs' => '/private/template/scan_irs_example.jpg',
                'tgl_registrasi' => '2024-08-01',
                'abstrak' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed at dui a nunc vestibulum ultricies. Nam condimentum lorem in tortor fermentum, at cursus justo ultricies. In hac habitasse platea dictumst. Nulla non purus arcu. Quisque auctor nulla id sapien mollis ultricies. Donec id elit ut magna euismod auctor. In eu tellus justo. Duis posuere mauris nec leo vestibulum malesuada. Nam eget augue ut leo aliquet egestas non id purus. Nam non luctus felis. Vivamus interdum hendrerit commodo. Nulla at felis ut justo egestas gravida. Aliquam non velit at lorem dictum sodales at at augue. Sed id justo at nisi ullamcorper eleifend a in risus. Donec dignissim libero id lacinia gravida. Integer porta justo vel odio sodales, sit amet facilisis sem volutpat.',
                'keyword1' => 'Keamanan Jaringan Komputer',
                'keyword2' => 'Analisis',
                'keyword3' => 'Keamanan',
                'link_berkas' => 'drive.google.com',
                'tgl_laporan' => '2024-09-01',
            ],
            [
                'nim' => '24060121100066',
                'status' => 'Laporan',
                'instansi' => 'PT. MNO',
                'judul' => 'Pengembangan Aplikasi Monitoring Lingkungan',
                'scan_irs' => '/private/template/scan_irs_example.jpg',
                'tgl_registrasi' => '2024-08-01',
                'abstrak' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed at dui a nunc vestibulum ultricies. Nam condimentum lorem in tortor fermentum, at cursus justo ultricies. In hac habitasse platea dictumst. Nulla non purus arcu. Quisque auctor nulla id sapien mollis ultricies. Donec id elit ut magna euismod auctor. In eu tellus justo. Duis posuere mauris nec leo vestibulum malesuada. Nam eget augue ut leo aliquet egestas non id purus. Nam non luctus felis. Vivamus interdum hendrerit commodo. Nulla at felis ut justo egestas gravida. Aliquam non velit at lorem dictum sodales at at augue. Sed id justo at nisi ullamcorper eleifend a in risus. Donec dignissim libero id lacinia gravida. Integer porta justo vel odio sodales, sit amet facilisis sem volutpat.',
                'keyword1' => 'Aplikasi Monitoring Lingkungan',
                'keyword2' => 'Pengembangan',
                'keyword3' => 'Lingkungan',
                'link_berkas' => 'drive.google.com',
                'tgl_laporan' => '2024-09-01',
            ],
            [
                'nim' => '24060121100067',
                'status' => 'Laporan',
                'instansi' => 'PT. PQR',
                'judul' => 'Pembuatan Sistem Informasi Manajemen Proyek',
                'scan_irs' => '/private/template/scan_irs_example.jpg',
                'tgl_registrasi' => '2024-08-01',
                'abstrak' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed at dui a nunc vestibulum ultricies. Nam condimentum lorem in tortor fermentum, at cursus justo ultricies. In hac habitasse platea dictumst. Nulla non purus arcu. Quisque auctor nulla id sapien mollis ultricies. Donec id elit ut magna euismod auctor. In eu tellus justo. Duis posuere mauris nec leo vestibulum malesuada. Nam eget augue ut leo aliquet egestas non id purus. Nam non luctus felis. Vivamus interdum hendrerit commodo. Nulla at felis ut justo egestas gravida. Aliquam non velit at lorem dictum sodales at at augue. Sed id justo at nisi ullamcorper eleifend a in risus. Donec dignissim libero id lacinia gravida. Integer porta justo vel odio sodales, sit amet facilisis sem volutpat.',
                'keyword1' => 'Sistem Informasi Manajemen Proyek',
                'keyword2' => 'Pembuatan',
                'keyword3' => 'Manajemen Proyek',
                'link_berkas' => 'drive.google.com',
                'tgl_laporan' => '2024-09-01',
            ],
            [
                'nim' => '24060121100068',
                'status' => 'Laporan',
                'instansi' => 'PT. STU',
                'judul' => 'Analisis dan Perancangan Basis Data',
                'scan_irs' => '/private/template/scan_irs_example.jpg',
                'tgl_registrasi' => '2024-08-01',
                'abstrak' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed at dui a nunc vestibulum ultricies. Nam condimentum lorem in tortor fermentum, at cursus justo ultricies. In hac habitasse platea dictumst. Nulla non purus arcu. Quisque auctor nulla id sapien mollis ultricies. Donec id elit ut magna euismod auctor. In eu tellus justo. Duis posuere mauris nec leo vestibulum malesuada. Nam eget augue ut leo aliquet egestas non id purus. Nam non luctus felis. Vivamus interdum hendrerit commodo. Nulla at felis ut justo egestas gravida. Aliquam non velit at lorem dictum sodales at at augue. Sed id justo at nisi ullamcorper eleifend a in risus. Donec dignissim libero id lacinia gravida. Integer porta justo vel odio sodales, sit amet facilisis sem volutpat.',
                'keyword1' => 'Analisis dan Perancangan Basis Data',
                'keyword2' => 'Analisis',
                'keyword3' => 'Basis Data',
                'link_berkas' => 'drive.google.com',
                'tgl_laporan' => '2024-09-01',
            ],
            [
                'nim' => '24060121100069',
                'status' => 'Laporan',
                'instansi' => 'PT. UVW',
                'judul' => 'Pembuatan Aplikasi Android',
                'scan_irs' => '/private/template/scan_irs_example.jpg',
                'tgl_registrasi' => '2024-08-01',
                'abstrak' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed at dui a nunc vestibulum ultricies. Nam condimentum lorem in tortor fermentum, at cursus justo ultricies. In hac habitasse platea dictumst. Nulla non purus arcu. Quisque auctor nulla id sapien mollis ultricies. Donec id elit ut magna euismod auctor. In eu tellus justo. Duis posuere mauris nec leo vestibulum malesuada. Nam eget augue ut leo aliquet egestas non id purus. Nam non luctus felis. Vivamus interdum hendrerit commodo. Nulla at felis ut justo egestas gravida. Aliquam non velit at lorem dictum sodales at at augue. Sed id justo at nisi ullamcorper eleifend a in risus. Donec dignissim libero id lacinia gravida. Integer porta justo vel odio sodales, sit amet facilisis sem volutpat.',
                'keyword1' => 'Aplikasi Android',
                'keyword2' => 'Pembuatan',
                'keyword3' => 'Android',
                'link_berkas' => 'drive.google.com',
                'tgl_laporan' => '2024-09-01',
            ],
            [
                'nim' => '24060121100070',
                'status' => 'Laporan',
                'instansi' => 'PT. WXY',
                'judul' => 'Analisis dan Perancangan Sistem Informasi',
                'scan_irs' => '/private/template/scan_irs_example.jpg',
                'tgl_registrasi' => '2024-08-01',
                'abstrak' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed at dui a nunc vestibulum ultricies. Nam condimentum lorem in tortor fermentum, at cursus justo ultricies. In hac habitasse platea dictumst. Nulla non purus arcu. Quisque auctor nulla id sapien mollis ultricies. Donec id elit ut magna euismod auctor. In eu tellus justo. Duis posuere mauris nec leo vestibulum malesuada. Nam eget augue ut leo aliquet egestas non id purus. Nam non luctus felis. Vivamus interdum hendrerit commodo. Nulla at felis ut justo egestas gravida. Aliquam non velit at lorem dictum sodales at at augue. Sed id justo at nisi ullamcorper eleifend a in risus. Donec dignissim libero id lacinia gravida. Integer porta justo vel odio sodales, sit amet facilisis sem volutpat.',
                'keyword1' => 'Analisis Sistem Informasi',
                'keyword2' => 'Analisis',
                'keyword3' => 'Sistem Informasi',
                'link_berkas' => 'drive.google.com',
                'tgl_laporan' => '2024-09-01',
            ],

            [
                'nim' => '24060121100071',
                'status' => 'Selesai',
                'instansi' => 'PT. ABC',
                'judul' => 'Pengembangan Aplikasi Manajemen Keuangan',
                'scan_irs' => '/private/template/scan_irs_example.jpg',
                'tgl_registrasi' => '2024-08-01',
                'abstrak' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed at dui a nunc vestibulum ultricies. Nam condimentum lorem in tortor fermentum, at cursus justo ultricies. In hac habitasse platea dictumst. Nulla non purus arcu. Quisque auctor nulla id sapien mollis ultricies. Donec id elit ut magna euismod auctor. In eu tellus justo. Duis posuere mauris nec leo vestibulum malesuada. Nam eget augue ut leo aliquet egestas non id purus. Nam non luctus felis. Vivamus interdum hendrerit commodo. Nulla at felis ut justo egestas gravida. Aliquam non velit at lorem dictum sodales at at augue. Sed id justo at nisi ullamcorper eleifend a in risus. Donec dignissim libero id lacinia gravida. Integer porta justo vel odio sodales, sit amet facilisis sem volutpat.',
                'keyword1' => 'Aplikasi Manajemen Keuangan',
                'keyword2' => 'Pengembangan',
                'keyword3' => 'Keuangan',
                'keyword4' => 'Sistem Informasi',
                'keyword5' => 'Analisis',
                'link_berkas' => 'drive.google.com',
                'tgl_laporan' => '2024-09-01',
                'tgl_verif_laporan' => '2024-09-02',
            ],
            [
                'nim' => '24060121100072',
                'status' => 'Selesai',
                'instansi' => 'PT. XYZ',
                'judul' => 'Analisis Sistem Informasi Penjualan',
                'scan_irs' => '/private/template/scan_irs_example.jpg',
                'tgl_registrasi' => '2024-08-01',
                'abstrak' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed at dui a nunc vestibulum ultricies. Nam condimentum lorem in tortor fermentum, at cursus justo ultricies. In hac habitasse platea dictumst. Nulla non purus arcu. Quisque auctor nulla id sapien mollis ultricies. Donec id elit ut magna euismod auctor. In eu tellus justo. Duis posuere mauris nec leo vestibulum malesuada. Nam eget augue ut leo aliquet egestas non id purus. Nam non luctus felis. Vivamus interdum hendrerit commodo. Nulla at felis ut justo egestas gravida. Aliquam non velit at lorem dictum sodales at at augue. Sed id justo at nisi ullamcorper eleifend a in risus. Donec dignissim libero id lacinia gravida. Integer porta justo vel odio sodales, sit amet facilisis sem volutpat.',
                'keyword1' => 'Sistem Informasi Penjualan',
                'keyword2' => 'Analisis',
                'keyword3' => 'Penjualan',
                'keyword4' => 'Manajemen',
                'keyword5' => 'Keuangan',
                'link_berkas' => 'drive.google.com',
                'tgl_laporan' => '2024-09-01',
                'tgl_verif_laporan' => '2024-09-02',
            ],
            [
                'nim' => '24060121100073',
                'status' => 'Selesai',
                'instansi' => 'PT. DEF',
                'judul' => 'Pengembangan Aplikasi Mobile Banking',
                'scan_irs' => '/private/template/scan_irs_example.jpg',
                'tgl_registrasi' => '2024-08-01',
                'abstrak' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed at dui a nunc vestibulum ultricies. Nam condimentum lorem in tortor fermentum, at cursus justo ultricies. In hac habitasse platea dictumst. Nulla non purus arcu. Quisque auctor nulla id sapien mollis ultricies. Donec id elit ut magna euismod auctor. In eu tellus justo. Duis posuere mauris nec leo vestibulum malesuada. Nam eget augue ut leo aliquet egestas non id purus. Nam non luctus felis. Vivamus interdum hendrerit commodo. Nulla at felis ut justo egestas gravida. Aliquam non velit at lorem dictum sodales at at augue. Sed id justo at nisi ullamcorper eleifend a in risus. Donec dignissim libero id lacinia gravida. Integer porta justo vel odio sodales, sit amet facilisis sem volutpat.',
                'keyword1' => 'Aplikasi Mobile Banking',
                'keyword2' => 'Pengembangan',
                'keyword3' => 'Banking',
                'keyword4' => 'Keuangan',
                'keyword5' => 'Sistem Informasi',
                'link_berkas' => 'drive.google.com',
                'tgl_laporan' => '2024-09-01',
                'tgl_verif_laporan' => '2024-09-03',
            ],
            [
                'nim' => '24060121100074',
                'status' => 'Selesai',
                'instansi' => 'PT. GHI',
                'judul' => 'Pengembangan Sistem Informasi Geografis',
                'scan_irs' => '/private/template/scan_irs_example.jpg',
                'tgl_registrasi' => '2024-08-01',
                'abstrak' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed at dui a nunc vestibulum ultricies. Nam condimentum lorem in tortor fermentum, at cursus justo ultricies. In hac habitasse platea dictumst. Nulla non purus arcu. Quisque auctor nulla id sapien mollis ultricies. Donec id elit ut magna euismod auctor. In eu tellus justo. Duis posuere mauris nec leo vestibulum malesuada. Nam eget augue ut leo aliquet egestas non id purus. Nam non luctus felis. Vivamus interdum hendrerit commodo. Nulla at felis ut justo egestas gravida. Aliquam non velit at lorem dictum sodales at at augue. Sed id justo at nisi ullamcorper eleifend a in risus. Donec dignissim libero id lacinia gravida. Integer porta justo vel odio sodales, sit amet facilisis sem volutpat.',
                'keyword1' => 'Sistem Informasi Geografis',
                'keyword2' => 'Pengembangan',
                'keyword3' => 'Geografis',
                'keyword4' => 'Analisis',
                'keyword5' => 'Data',
                'link_berkas' => 'drive.google.com',
                'tgl_laporan' => '2024-09-01',
                'tgl_verif_laporan' => '2024-09-03',
            ],
            [
                'nim' => '24060121100075',
                'status' => 'Selesai',
                'instansi' => 'PT. JKL',
                'judul' => 'Analisis dan Perancangan Basis Data',
                'scan_irs' => '/private/template/scan_irs_example.jpg',
                'tgl_registrasi' => '2024-08-01',
                'abstrak' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed at dui a nunc vestibulum ultricies. Nam condimentum lorem in tortor fermentum, at cursus justo ultricies. In hac habitasse platea dictumst. Nulla non purus arcu. Quisque auctor nulla id sapien mollis ultricies. Donec id elit ut magna euismod auctor. In eu tellus justo. Duis posuere mauris nec leo vestibulum malesuada. Nam eget augue ut leo aliquet egestas non id purus. Nam non luctus felis. Vivamus interdum hendrerit commodo. Nulla at felis ut justo egestas gravida. Aliquam non velit at lorem dictum sodales at at augue. Sed id justo at nisi ullamcorper eleifend a in risus. Donec dignissim libero id lacinia gravida. Integer porta justo vel odio sodales, sit amet facilisis sem volutpat.',
                'keyword1' => 'Analisis Basis Data',
                'keyword2' => 'Analisis',
                'keyword3' => 'Basis Data',
                'keyword4' => 'Perancangan',
                'keyword5' => 'Sistem Informasi',
                'link_berkas' => 'drive.google.com',
                'tgl_laporan' => '2024-09-01',
                'tgl_verif_laporan' => '2024-09-04',
            ],
            [
                'nim' => '24060121100076',
                'status' => 'Selesai',
                'instansi' => 'PT. MNO',
                'judul' => 'Pembuatan Aplikasi Manajemen Proyek',
                'scan_irs' => '/private/template/scan_irs_example.jpg',
                'tgl_registrasi' => '2024-08-01',
                'abstrak' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed at dui a nunc vestibulum ultricies. Nam condimentum lorem in tortor fermentum, at cursus justo ultricies. In hac habitasse platea dictumst. Nulla non purus arcu. Quisque auctor nulla id sapien mollis ultricies. Donec id elit ut magna euismod auctor. In eu tellus justo. Duis posuere mauris nec leo vestibulum malesuada. Nam eget augue ut leo aliquet egestas non id purus. Nam non luctus felis. Vivamus interdum hendrerit commodo. Nulla at felis ut justo egestas gravida. Aliquam non velit at lorem dictum sodales at at augue. Sed id justo at nisi ullamcorper eleifend a in risus. Donec dignissim libero id lacinia gravida. Integer porta justo vel odio sodales, sit amet facilisis sem volutpat.',
                'keyword1' => 'Aplikasi Manajemen Proyek',
                'keyword2' => 'Pembuatan',
                'keyword3' => 'Manajemen',
                'keyword4' => 'Keuangan',
                'keyword5' => 'Proyek',
                'link_berkas' => 'drive.google.com',
                'tgl_laporan' => '2024-09-01',
                'tgl_verif_laporan' => '2024-09-04',
            ],
            [
                'nim' => '24060121100077',
                'status' => 'Selesai',
                'instansi' => 'PT. PQR',
                'judul' => 'Pengembangan Aplikasi E-Commerce',
                'scan_irs' => '/private/template/scan_irs_example.jpg',
                'tgl_registrasi' => '2024-08-01',
                'abstrak' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed at dui a nunc vestibulum ultricies. Nam condimentum lorem in tortor fermentum, at cursus justo ultricies. In hac habitasse platea dictumst. Nulla non purus arcu. Quisque auctor nulla id sapien mollis ultricies. Donec id elit ut magna euismod auctor. In eu tellus justo. Duis posuere mauris nec leo vestibulum malesuada. Nam eget augue ut leo aliquet egestas non id purus. Nam non luctus felis. Vivamus interdum hendrerit commodo. Nulla at felis ut justo egestas gravida. Aliquam non velit at lorem dictum sodales at at augue. Sed id justo at nisi ullamcorper eleifend a in risus. Donec dignissim libero id lacinia gravida. Integer porta justo vel odio sodales, sit amet facilisis sem volutpat.',
                'keyword1' => 'Aplikasi E-Commerce',
                'keyword2' => 'Pengembangan',
                'keyword3' => 'E-Commerce',
                'keyword4' => 'Sistem Informasi',
                'keyword5' => 'Pembuatan',
                'link_berkas' => 'drive.google.com',
                'tgl_laporan' => '2024-09-01',
                'tgl_verif_laporan' => '2024-09-05',
            ],
            [
                'nim' => '24060121100078',
                'status' => 'Selesai',
                'instansi' => 'PT. STU',
                'judul' => 'Analisis dan Perancangan Sistem Informasi Geografis',
                'scan_irs' => '/private/template/scan_irs_example.jpg',
                'tgl_registrasi' => '2024-08-01',
                'abstrak' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed at dui a nunc vestibulum ultricies. Nam condimentum lorem in tortor fermentum, at cursus justo ultricies. In hac habitasse platea dictumst. Nulla non purus arcu. Quisque auctor nulla id sapien mollis ultricies. Donec id elit ut magna euismod auctor. In eu tellus justo. Duis posuere mauris nec leo vestibulum malesuada. Nam eget augue ut leo aliquet egestas non id purus. Nam non luctus felis. Vivamus interdum hendrerit commodo. Nulla at felis ut justo egestas gravida. Aliquam non velit at lorem dictum sodales at at augue. Sed id justo at nisi ullamcorper eleifend a in risus. Donec dignissim libero id lacinia gravida. Integer porta justo vel odio sodales, sit amet facilisis sem volutpat.',
                'keyword1' => 'Analisis Sistem Informasi Geografis',
                'keyword2' => 'Analisis',
                'keyword3' => 'Geografis',
                'keyword4' => 'Pengembangan',
                'keyword5' => 'Sistem Informasi',
                'link_berkas' => 'drive.google.com',
                'tgl_laporan' => '2024-09-01',
                'tgl_verif_laporan' => '2024-09-05',
            ],
            [
                'nim' => '24060121100079',
                'status' => 'Selesai',
                'instansi' => 'PT. VWX',
                'judul' => 'Pembuatan Aplikasi Mobile Learning',
                'scan_irs' => '/private/template/scan_irs_example.jpg',
                'tgl_registrasi' => '2024-08-01',
                'abstrak' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed at dui a nunc vestibulum ultricies. Nam condimentum lorem in tortor fermentum, at cursus justo ultricies. In hac habitasse platea dictumst. Nulla non purus arcu. Quisque auctor nulla id sapien mollis ultricies. Donec id elit ut magna euismod auctor. In eu tellus justo. Duis posuere mauris nec leo vestibulum malesuada. Nam eget augue ut leo aliquet egestas non id purus. Nam non luctus felis. Vivamus interdum hendrerit commodo. Nulla at felis ut justo egestas gravida. Aliquam non velit at lorem dictum sodales at at augue. Sed id justo at nisi ullamcorper eleifend a in risus. Donec dignissim libero id lacinia gravida. Integer porta justo vel odio sodales, sit amet facilisis sem volutpat.',
                'keyword1' => 'Aplikasi Mobile Learning',
                'keyword2' => 'Pembuatan',
                'keyword3' => 'Mobile Learning',
                'keyword4' => 'Analisis',
                'keyword5' => 'Pengembangan',
                'link_berkas' => 'drive.google.com',
                'tgl_laporan' => '2024-09-01',
                'tgl_verif_laporan' => '2024-09-06',
            ],
            [
                'nim' => '24060121100080',
                'status' => 'Selesai',
                'instansi' => 'PT. YZB',
                'judul' => 'Analisis dan Perancangan Sistem Informasi Keuangan',
                'scan_irs' => '/private/template/scan_irs_example.jpg',
                'tgl_registrasi' => '2024-08-01',
                'abstrak' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed at dui a nunc vestibulum ultricies. Nam condimentum lorem in tortor fermentum, at cursus justo ultricies. In hac habitasse platea dictumst. Nulla non purus arcu. Quisque auctor nulla id sapien mollis ultricies. Donec id elit ut magna euismod auctor. In eu tellus justo. Duis posuere mauris nec leo vestibulum malesuada. Nam eget augue ut leo aliquet egestas non id purus. Nam non luctus felis. Vivamus interdum hendrerit commodo. Nulla at felis ut justo egestas gravida. Aliquam non velit at lorem dictum sodales at at augue. Sed id justo at nisi ullamcorper eleifend a in risus. Donec dignissim libero id lacinia gravida. Integer porta justo vel odio sodales, sit amet facilisis sem volutpat.',
                'keyword1' => 'Analisis Sistem Informasi Keuangan',
                'keyword2' => 'Analisis',
                'keyword3' => 'Keuangan',
                'keyword4' => 'Manajemen',
                'keyword5' => 'Sistem Informasi',
                'link_berkas' => 'drive.google.com',
                'tgl_laporan' => '2024-09-01',
                'tgl_verif_laporan' => '2024-09-06',
            ],

        ];

        foreach ($pkl as $data) {
            PKL::create($data);
        }
    }
}
